export const state = {
  headers: [
    {
      title: 'Действие',
      align: 'start',
      sortable: false,
      key: 'action',
      show: true,
    },
    {
      title: 'Наименование еденицы',
      align: 'start',
      sortable: false,
      key: 'name',
      show: true,
    },

    { title: 'Новая колонка', align: 'start', sortable: false, key: 'newCol', show: true },

    { title: 'Цена', align: 'start', sortable: false, key: 'price', show: true },
    { title: 'Кол-во', align: 'start', sortable: false, key: 'quantity', show: true },
    {
      title: 'Название товара',
      align: 'start',
      sortable: false,
      key: 'product',
      show: true,
    },
    { title: 'Итого', align: 'start', sortable: false, key: 'total', show: true },
  ],
  headerActive: {},
  products: [
    {
      id: 1,
      action: 'действие',
      name: 'Серебренный щебень фр. 2-5 мм, 25кг',
      newCol: 'Новая колонка',
      price: 1203,
      quantity: 10,
      product: 'Мраморный щебе',
      total: '15623',
    },
    {
      id: 2,
      action: 'действие',
      name: 'Золотой щебень фр. 2-5 мм, 25кг.  Серебренный щебень фр.',
      newCol: 'Новая колонка',
      price: 1203,
      quantity: 20,
      product: 'Мраморный щебе',
      total: '15623',
    },
    {
      id: 3,
      action: 'действие',
      name: 'Мраморный щебень фр. 2-5 мм, 25кг',
      newCol: 'Новая колонка',
      price: 1203,
      quantity: 30,
      product: 'Мраморный щебе',
      total: '15623',
    },
    {
      id: 4,
      action: 'действие',
      name: 'Мраморный щебень фр. 2-5 мм, 25кг. Золотой щебень фр. 2-5 мм, 25кг.  Серебренный щебень фр.',
      newCol: 'Новая колонка',
      price: 1203,
      quantity: 40,
      product: 'Мраморный щебе',
      total: '15623',
    },
  ],

  changeColumns: false,
  activeLineEdit: {},
  menuWindow: false,
};
